before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/atget
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
checksum:
  name_template: "checksums.txt"
archives:
  - format_overrides:
      - goos: windows
        format: zip
